name: build-and-push

on:
  push:
    branches: [ main ]  # or use tags if you prefer

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare artifacts directory
        run: mkdir -p artifacts

      - name: Install Tor and fetch artifacts over Tor (v1.0.0, amd64)
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y tor torsocks gnupg curl coreutils
          cat > /tmp/torrc <<'EOF'
          RunAsDaemon 0
          DataDirectory /var/lib/tor
          ClientOnly 1
          AvoidDiskWrites 1
          SocksPort 127.0.0.1:9050
          Log notice stdout
          EOF
          tor -f /tmp/torrc &
          for i in $(seq 1 60); do
            (echo > /dev/tcp/127.0.0.1/9050) >/dev/null 2>&1 && break
            sleep 1
            if [ "$i" -eq 60 ]; then echo "Tor SOCKS not ready"; exit 1; fi
          done
          torsocks wget -O artifacts/ashigaru_terminal_v1.0.0_amd64.deb \
            "http://ashicodepbnpvslzsl2bz7l2pwrjvajgumgac423pp3y2deprbnzz7id.onion/Ashigaru/Ashigaru-Terminal/releases/download/v1.0.0/ashigaru_terminal_v1.0.0_amd64.deb"
          torsocks wget -O artifacts/ashigaru_terminal_v1.0.0_signed_hashes.txt \
            "http://ashicodepbnpvslzsl2bz7l2pwrjvajgumgac423pp3y2deprbnzz7id.onion/Ashigaru/Ashigaru-Terminal/releases/download/v1.0.0/ashigaru_terminal_v1.0.0_signed_hashes.txt"
          curl -sS https://keybase.io/ashigarudev/pgp_keys.asc | gpg --import
          gpg --verify artifacts/ashigaru_terminal_v1.0.0_signed_hashes.txt
          exp=$(awk '/File name: ashigaru_terminal_v1.0.0_amd64.deb/{getline; print $NF; exit}' artifacts/ashigaru_terminal_v1.0.0_signed_hashes.txt)
          [ -n "$exp" ] && [ "${#exp}" -eq 64 ]
          act=$(sha256sum artifacts/ashigaru_terminal_v1.0.0_amd64.deb | awk '{print $1}')
          test "$exp" = "$act"

      - name: Set up QEMU (for multi-arch build)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image metadata
        id: vars
        run: |
          echo "repo=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
          echo "version=1.0.0" >> $GITHUB_OUTPUT
          echo "icon_url=https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/main/assets/icon.png" >> $GITHUB_OUTPUT
          echo "tags=ghcr.io/${GITHUB_REPOSITORY,,}:1.0.0,ghcr.io/${GITHUB_REPOSITORY,,}:latest" >> $GITHUB_OUTPUT

      - name: Build and push multi-arch (amd64 + arm64 via qemu)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          provenance: false
          tags: ${{ steps.vars.outputs.tags }}
          build-args: |
            ASHI_VERSION=${{ steps.vars.outputs.version }}
            ICON_URL=${{ steps.vars.outputs.icon_url }}
